version: "3.9"

services:
  frontend:
    container_name: portfolio_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3110:9000"          # host:container â†’ safe range (no clash with Traefik)
    restart: unless-stopped

